/*
* generated by Xtext
*/
package org.uqbar.mingus.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MingusOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
