/*
 * generated by Xtext
 */
package org.uqbar.mingus.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MingusUiModule extends org.uqbar.mingus.ui.AbstractMingusUiModule {
	public MingusUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
