/*
 * generated by Xtext
 */
package org.uqbar.mingus;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MingusRuntimeModule extends org.uqbar.mingus.AbstractMingusRuntimeModule {

}
