/*
* generated by Xtext
*/
package org.uqbar.mingus.ui.contentassist;

import org.uqbar.mingus.ui.contentassist.AbstractMingusProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MingusProposalProvider extends AbstractMingusProposalProvider {

}
